Mask como extension
mercadolibre/fury_andesui-android pull request #145
Opened 2020-09-09 19:31 UTC by nesmarsollie

### Thanks for starting a pull request on Andes UI!

## Useful links
- [Contributing](https://github.com/mercadolibre/fury_andesui-android/blob/develop/CONTRIBUTING.md) has more information and tips for a great pull request. This will give you a nice introduction about how to contribute with Andes.
- [Wiki](https://github.com/mercadolibre/fury_andesui-android/wiki) has all the info you need to start with Andes. Even I heard there's a video there...

## Motivation
Tell us why you are here and why you took time to develop new code for our beloved lib.

## Description
Please describe your intentions with this new code you want to introduce inside Andes UI lib.
Try to answer those questions:
- What is it about?
- How does it work?

## Affected component
Is highly probable that this new code directly affects one (or more?) components inside this lib. Tell us who they are!

## Frontify component link
The UX team behind Andes keeps all the Andes Components inside the Frontify site. Each component has its own section. Let us know the section of the component you want to modify.

## Screenshots
This is a UI library, delight us with some stunning images.

## Checks
Are you sure you followed all those steps? In such case, let's say with me "I solemnly declare that ...":
- [ ] I have coded an example inside the Demo App,
- [ ] I have added proper tests,
- [ ] I have modified the [Changelog](https://github.com/mercadolibre/fury_andesui-android/blob/develop/CHANGELOG.md) file,
- [ ] I have updated GitHub wiki,
- [ ] I have the explicit approval of one or more members of the UX Team,
- [ ] I have updated the version in gradle.properties file.

## Change type
This is easy, let us know what this code is about:
- [ ] This code adds a new component
- [ ] This code includes improvements to an existent component
- [ ] This code improves or modifies ONLY the Demo App.

## Check common errors
Whether you are an Android or iOS developer and if you're still there then we'll give you a present:
https://proandroiddev.com/how-to-maximize-androids-ui-reusability-5-common-mistakes-cb2571216a9f

2020-09-09 19:31 UTC, furyGorgoryAdmin commented
### Informative Menu <h2>  ### 

### Use any of these tags in a pull request description or leave a comment ### 
| Tag | Description |
|---|---|
| **[canary]**| Creates a build that can only be deployed with canary strategy. | 
| **[build]** |  Creates version or build from a branch that has been tagged as "no releasable". | 
| **[name:version-name]** |Specify the name of the build. For example: [build] [name:1.2.3-name] or [canary] [name:1.2.3-name].|
| **[major]** | To automatically increase the first position of the version. For example: [build] [major] or [canary] [major].|
| **[minor]** | To automatically increase the second position of the version. For example: [build] [minor] or [canary] [minor]. |
| **[patch]** | To automatically increase the third position of the version. For example: [build] [patch] or [canary] [patch].|  

[For more information about ci-cd](http://docs.furycloud.io/?lang=esp&section=businessassurance)
[For more information about semver](https://semver.org/#summary)

2020-09-09 23:47 UTC, nesmarsollie commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +            textComponent.setText(value)
Ahora el behaviour se encarga de aplicar la mascara que corresponda

2020-09-09 23:47 UTC, nesmarsollie commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +            field = value
La verdad no me convencia usar andesTextfieldAttrs para el watcher. No veo practico un watcher aplicado como atributo

2020-09-09 23:47 UTC, nesmarsollie commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +            setupFilters()
Para mantener convencion de nombres de stups

2020-09-09 23:47 UTC, nesmarsollie commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +
Este es el nuevo modelo, lo bueno es que podemos hacer cleanup y la implementacion se encargara de limpiar lo que configure

2020-09-09 23:47 UTC, nesmarsollie commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +        countFilter = object : InputFilter {
Este filter es uno solo, se configura una sola vez. No cambia porque en realidad es interno y dinamico.

2020-09-09 23:47 UTC, nesmarsollie commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +        textComponent.addTextChangedListener(object : TextWatcher {
El problema anterior era que este counter no se reseteaba, al ser un TextChangeListener tendiramos que quitarlo y agregarlo.
Con esta estrategia no quito nada, es uno solo, que onTextChanged se adaptar adecuadamente.

2020-09-17 17:53 UTC, juanimoli requested changes
dado que no hay reporte de coverage por ahora, porfa agreguemos tests de la lógica nueva y también de la vieja si es que quedó mejor modularizada!

2020-09-17 17:53 UTC, juanimoli commented on components/src/main/java/com/mercadolibre/android/andesui/badge/AndesBadgePill.kt
> +    @SuppressWarnings("MagicNumber")
no suprimiría estos warnings. Si vamos por suprimirlos, preferiría por explicar porque elegimos arbitrariamente los números del `config.backgroundRadius[N]`

2020-09-17 17:53 UTC, juanimoli commented on components/src/main/java/com/mercadolibre/android/andesui/progress/LoadingSpinner.kt
> +    @SuppressWarnings("MagicNumber")
idem estos ;)

2020-09-17 17:53 UTC, juanimoli commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +            textComponent.removeTextChangedListener(field)
`field` podría ser nulo, `removeTextChangeListener()` es NPSafe?

2020-09-17 17:53 UTC, juanimoli commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +        action.isEnabled = state != READONLY && state != AndesTextfieldState.DISABLED
mantengamos una convención porfa, si todos son `AndesTextfieldState` o hacemos import de todos removiendo el acceso directo, o todos directos

2020-09-17 17:53 UTC, juanimoli commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +                counterAdapter?.invoke("") ?: 0,
por qué removimos el método? de última podríamos adaptar la lógica del método sin removerlo. Ayudaría a entender el código ya que podríamos agregarle KDoc

2020-09-17 17:53 UTC, juanimoli commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +        countFilter = object : InputFilter {
le agregamos algo de documentación porfa?

2020-09-17 17:53 UTC, juanimoli commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +            @SuppressWarnings("EmptyFunctionBlock")
no se suprimen con un comentario en el método?

2020-09-17 17:53 UTC, juanimoli commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +    interface Behaviour {
le agregamos algo de documentación también? sobretodo a los métodos dado que esto lo vamos a poder inyectar desde cualquier lado

2020-09-17 17:53 UTC, juanimoli commented on config/detekt/detekt.yml
> +    excludes: "**/test/**,**/demoapp/**,**/androidTest/**,**/*.Test.kt,**/*.Spec.kt,**/*.Spek.kt"
por qué excluimos la `demoapp`?

2020-09-17 17:53 UTC, juanimoli commented on demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/MessageShowcaseActivity.kt
> +import android.annotation.SuppressLint
lo necesitamos?

2020-09-17 17:53 UTC, juanimoli commented on demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/TextfieldShowcaseActivity.kt
> +import android.annotation.SuppressLint
idem

2020-09-17 17:53 UTC, juanimoli commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/bahaviours/MaskBehaviour.kt
> +private class TextFieldMaskWatcher(
podríamos pasarlo a una clase aparte?

2020-09-17 17:53 UTC, juanimoli commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/factory/AndesTexfieldAttrsParser.kt
> -    val textWatcher: TextWatcher? = null
podríamos pasarle como atributo también el behaviour?

2020-09-17 18:49 UTC, nesmarsollie commented on components/src/main/java/com/mercadolibre/android/andesui/progress/LoadingSpinner.kt
> +    @SuppressWarnings("MagicNumber")
Y como que en si mismo un @SupressWarning dice lo suficiente. Bah no se es mi punto de vista. Se suprime porque es un error de linter, y el valor esta bien como valor en si mismo.

2020-09-17 18:49 UTC, nesmarsollie commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +            textComponent.removeTextChangedListener(field)
si permite nulos sin problemas.

2020-09-17 18:49 UTC, nesmarsollie commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +                counterAdapter?.invoke("") ?: 0,
Porque ahora esta delegada la responsabilidad de saber cuanto es el tamaño correcto.
En mascaras el tamaño no es el getTextLength() sino que depende de la mascara puede que sea una funcion especifica, dependiente del negocio.

2020-09-17 18:49 UTC, nesmarsollie commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +            @SuppressWarnings("EmptyFunctionBlock")
Si, pero porque comentar algo que debe ser vacío. 
Personalmente veo a los SupressWarning como algo premeditado que tiene sentido que sea asi. Comentar para que no salte un linter es mas o menos el mismo efecto, pero que pondrias en este caso ? 
// Lorem ipsum...
Bah no se como lo llevan.

2020-09-17 18:49 UTC, nesmarsollie commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/bahaviours/MaskBehaviour.kt
> +private class TextFieldMaskWatcher(
No lo veo conveninte, estoy encapsulando codigo que no debe tener sentido fuera de esta clase.
Si fuera java seria una clase anidada.

2020-09-17 18:49 UTC, nesmarsollie commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/factory/AndesTexfieldAttrsParser.kt
> -    val textWatcher: TextWatcher? = null
Uff, todavia no entiendo esta clase, sin ofender pero la veo como un antipatron de las buenas practicas de android.
Ya de por si es una bolsa de gatos, si le metemos mas cosas, ya no se si son atributos, o propiedades internas de la clase extenalizadas por alguna razon.
Sin embargo la simplificacion del codigo es la clave en todo esto, y veo que es mas legible y simple desacoplar los behabiours de esta clase.

2020-09-17 18:49 UTC, nesmarsollie commented on config/detekt/detekt.yml
> +    excludes: "**/test/**,**/demoapp/**,**/androidTest/**,**/*.Test.kt,**/*.Spec.kt,**/*.Spek.kt"
Ahh me molestaba esa regla, en la demo app basicamete hay reglas que podrian ser flexibles.
Considero la demo app como una aplicacion que debe codearse rapidamente y con ciertas flexibilidades a la hora de chequear reglas. 
Relgas como maxLineNumber, y magicNumbers, y no se si suman en la demo.
De hecho una constante que solo se usa en un solo lado, es una constante que no tiene sentido definir.
Escucho opiniones.

2020-09-17 18:49 UTC, nesmarsollie commented on demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/TextfieldShowcaseActivity.kt
> +import android.annotation.SuppressLint
Ni idea porque se agregaron

2020-09-17 18:49 UTC, nesmarsollie commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +    interface Behaviour {
si

2020-09-17 18:49 UTC, nesmarsollie commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +        action.isEnabled = state != READONLY && state != AndesTextfieldState.DISABLED
Correcto, igual es legacy esto.

2020-10-20 18:52 UTC, barriosnahuel reviewed
acabo de ver que super colgamos este PR! le das una mirada a los comentarios @nesmarsollie y lo mergeamos?

2020-10-20 18:52 UTC, barriosnahuel commented on components/src/main/java/com/mercadolibre/android/andesui/badge/AndesBadgePill.kt
> +    @SuppressWarnings("MagicNumber")
+1, @nesmarsollie podemos hacelros una constante así queda más claro qué son por fa?

2020-10-20 18:52 UTC, barriosnahuel commented on components/src/main/java/com/mercadolibre/android/andesui/progress/LoadingSpinner.kt
> +    @SuppressWarnings("MagicNumber")
ojo, el suppressWarning solo te dice que lo queres ignorar, pero en ningún momento estamos aclarando por qué. Si es un falso positivo o es algo que para este caso de uso puntual elegimos hacer de otra manera (por eso los suppress más nuevos incluso te obligan a completar una justificación dentro de la anotation.

los dos 0 se podrían pasar a una única constante initial_angle y creo que estaría bien, pero el strokeSize sí está bueno aclarar por ej en la constante incluso hasta qué unidad es: px o dp? qué opinan?

2020-10-20 18:52 UTC, barriosnahuel commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +                counterAdapter?.invoke("") ?: 0,
el invoke entonces esta resolviendo el getTextLength? queda poco legible si no conoces la imple.. qué pasaría si dejamos el método getTextLength con esta imple del adapter.invoke?

por otro lado, podría pasar que el adapter sea nulo? qué pasaría en ese caso?

2020-10-20 18:52 UTC, barriosnahuel commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +            @SuppressWarnings("EmptyFunctionBlock")
históricamente venimos poniendo:

```
xxx {
    // Do nothing
}
```

y creo que queda más claro para el que viene después que "realmente no queremos hacer nada" en este método.

Al poner el suppressWarnings así solo podría ser que solo queremos apagar el linter pero en ningún momento le aclaramos al lector que "la imple es no hacer nada".. me explico?
En todo caso podríamos dejar el suppressWarnings pero agregando el atributo justification y explicando por qué lo apagamos, ej: "realmente no quermeos hacer nada"

cómo lo ves?

2020-10-20 18:52 UTC, barriosnahuel commented on config/detekt/detekt.yml
> +    excludes: "**/test/**,**/demoapp/**,**/androidTest/**,**/*.Test.kt,**/*.Spec.kt,**/*.Spek.kt"
coincido que queremos ser más flexibles en las testapps, sin embargo el fin último de los linters creo que es aprender las buenas prácticas (no solo corregir cosas cuando tira rojo). Con esto en mente, si podemos hacer código de calidad incluso en las testapps (y que esta sea la forma default en la que todos escribimos código), por qué no hacerlo?
maxLineNumber y magicNumbers no veo que agreguen fricciones en el desarrollo o que nos hagan "ir más lento", qué beneficio ves en apagarlos? Ej: max line number si lo tenemos prendido para el módulo productivo, al tener el IDE bien configurado ya tenemos gratis respetar la rule en la testapp.

estamos tratando de alineaer cad vez más los checks a nivel cross Meli así que dentro de lo posible por ahora trataría de esto revertirlo salvo que sea extremadamente necesario..

2020-10-21 15:53 UTC, nesmarsollie reviewed
Ahi cuando tenga un rato arreglo algunas cosas de tus comentarios.

2020-10-21 15:53 UTC, nesmarsollie commented on components/src/main/java/com/mercadolibre/android/andesui/badge/AndesBadgePill.kt
> +    @SuppressWarnings("MagicNumber")
con MagicNumber , los números siguen siendo arbitrarios solo que están definidos en una constante.
Personalmente me parece un error definir una constante cuando no tiene un significado como tal,  no ponerlos en el lugar que corresponde solo arruina la lectura.
Personalmente MagicNumber es un error conceptual que generaliza  que debe o no estar como constante.

2020-10-21 15:53 UTC, nesmarsollie commented on components/src/main/java/com/mercadolibre/android/andesui/progress/LoadingSpinner.kt
> +    @SuppressWarnings("MagicNumber")
Ufff, no, tenemos puntos de vista muy alejados.
En cualquier lenguaje un numero puesto como tal, por ejemplo 0 es una constante en el lenguaje.
Estratégicamente hablando una constante como initial_ange a mí me dice mucho más que solo un numero que evita un linter. El linter esta mal en este caso.
Si vos definís una constante es porque en algún momento la querés cambiar, o porque se reusa y querés que quede claro que es ese significado, por ejemplo SITE_MLA = "MLA", tiene sentido porque es la constante MLA que no queres repetir y de paso evitar errores.
Otra constante que tiene sentido seria algun libraryVersion, donde vos en algun momento queres actualizar la version y esta bien, es constante pero va a cambiar.

Esto de poner todos los numeros y valores en constantes es un error comun, pero en realidad solo terminan arruinando la lectura del codigo.

2020-10-21 15:53 UTC, nesmarsollie commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +                counterAdapter?.invoke("") ?: 0,
Puede ser en una funcion, para simplificar la lectura. Pero el nombre propondria que fuera diferente. El text length puede ser distinto del counter, y este es el sentido de esta estrategia, basicamnete decir el counter de caracteres es diferente al length real del string.
Podria ser una funcion getTextCounter() quizas.

2020-10-21 15:53 UTC, nesmarsollie commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +            @SuppressWarnings("EmptyFunctionBlock")
Y a mi siempre me suena a que 
// Do nothing 
realmente suena a trick para evitar el linter.

En este caso me da igual , al final cuando leo el codigo a mi me dice lo mismo. El programador deliberadamente quiere expresar que la funcion debe estar vacia, y esta bien asi.

2020-10-21 15:53 UTC, nesmarsollie commented on config/detekt/detekt.yml
> +    excludes: "**/test/**,**/demoapp/**,**/androidTest/**,**/*.Test.kt,**/*.Spec.kt,**/*.Spek.kt"
MagicNumber realmente lo veo un error conceptualmente.

El maxLineNumber lo veo bien, se equivoca a veces nomas.

2020-10-21 16:20 UTC, barriosnahuel commented on components/src/main/java/com/mercadolibre/android/andesui/progress/LoadingSpinner.kt
> +    @SuppressWarnings("MagicNumber")
no digo de poner todo, sino lo que nos haga sentido.. creo que estamos llevando la charla más a filosofía en lugar de ver qué es lo que más nos conviene (a nosotros mismos) en 6 meses por ej. A lo que voy es, me da igual si dejamos el suppress o pasamos el 0 a una constante, siempre y cuando:
- si dejamos el suppress le ponemos un comentario o una justificación indicando por qué lo estamos apagando
- si lo pasamos a una constante queda claro qué es lo que representa

si preferis dejar el suppress solamente agrega la justificación y listo =)

2020-10-21 16:20 UTC, barriosnahuel commented on components/src/main/java/com/mercadolibre/android/andesui/badge/AndesBadgePill.kt
> +    @SuppressWarnings("MagicNumber")
el punto no es si son arbitrarios creo, sino que quede claro qué representan. Al ponerlos en una constante les vamos a poner un nombre, e incluso hsata podemos documentar qué significa o "de donde sale". Ves algún problema con eso?

Creo que te super puede interesar la iniciativa de Fury sobre la herramienta de chequeo de código, ahí te la paso por privado así no queda en este repo que es open source :P

2020-10-21 16:20 UTC, barriosnahuel commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +                counterAdapter?.invoke("") ?: 0,
claro! excelente

2020-10-21 16:20 UTC, barriosnahuel commented on components/src/main/java/com/mercadolibre/android/andesui/textfield/AndesTextfield.kt
> +            @SuppressWarnings("EmptyFunctionBlock")
trataría de dejarlo con el comentario para mantener la convención que venimos teniendo en todos los otros proeyctos, te parece?

2020-11-30 14:04 UTC, snti submitted a review, later dismissed

2021-01-09 14:40 UTC, closed without merging