Feature/spsbdev 1674
mercadolibre/fury_andesui-android pull request #180
Opened 2020-11-05 18:43 UTC by AdrianDeSeta1985

### Thanks for starting a pull request on Andes UI!

## Useful links
- [Contributing](https://github.com/mercadolibre/fury_andesui-android/blob/develop/CONTRIBUTING.md) has more information and tips for a great pull request. This will give you a nice introduction about how to contribute with Andes.
- [Wiki](https://github.com/mercadolibre/fury_andesui-android/wiki) has all the info you need to start with Andes. Even I heard there's a video there...

## Motivation
Tell us why you are here and why you took time to develop new code for our beloved lib.

## Description
Please describe your intentions with this new code you want to introduce inside Andes UI lib.
Try to answer those questions:
- What is it about?
- How does it work?

## Affected component
Is highly probable that this new code directly affects one (or more?) components inside this lib. Tell us who they are!

## Frontify component link
The UX team behind Andes keeps all the Andes Components inside the Frontify site. Each component has its own section. Let us know the section of the component you want to modify.

## Screenshots
This is a UI library, delight us with some stunning images.

## Checks
Are you sure you followed all those steps? In such case, let's say with me "I solemnly declare that ...":
- [ ] I have coded an example inside the Demo App,
- [ ] I have added proper tests,
- [ ] I have modified the [Changelog](https://github.com/mercadolibre/fury_andesui-android/blob/develop/CHANGELOG.md) file,
- [ ] I have updated GitHub wiki,
- [ ] I have the explicit approval of one or more members of the UX Team,
- [ ] I have updated the version in gradle.properties file.

## Change type
This is easy, let us know what this code is about:
- [ ] This code adds a new component
- [ ] This code includes improvements to an existent component
- [ ] This code improves or modifies ONLY the Demo App.

## Check common errors
Whether you are an Android or iOS developer and if you're still there then we'll give you a present:
https://proandroiddev.com/how-to-maximize-androids-ui-reusability-5-common-mistakes-cb2571216a9f

2020-11-06 13:03 UTC, snti commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +        //TODO AndesDatePicker: Update UI
Este TODO creo q ya no seria necesario

2020-11-06 13:08 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +        //TODO AndesDatePicker: Update UI
removido en el commit "comentarios removidos"

2020-11-06 13:13 UTC, snti commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/factory/AndesDatePickerAttrsParser.kt
> +        //TODO AndesDatePicker: Add into build.gradle 'src/main/res/datepicker'
idem

2020-11-06 13:18 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/factory/AndesDatePickerAttrsParser.kt
> +        //TODO AndesDatePicker: Add into build.gradle 'src/main/res/datepicker'
resuelto en commit  "comentarios removidos parser"

2020-11-06 13:23 UTC, snti commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +    var listener: ApplyDatePickerClickListener? = null
quizas esta variable la podemos mover al principio de la clase

2020-11-06 13:28 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +    var listener: ApplyDatePickerClickListener? = null
resuelto en "interface fix"

2020-11-06 13:38 UTC, snti commented on demoapp/src/main/res/layout/andesui_demoapp_main.xml
El boton tendria que ir entre el Coachmark y el Message, para seguir respetando el orden alfabetico.

2020-11-06 13:47 UTC, AdrianDeSeta1985 commented on demoapp/src/main/res/layout/andesui_demoapp_main.xml
resuelto en "button andesDatepicker reubicado en home"

2020-11-11 19:13 UTC, AdrianDeSeta1985 commented
> Capaz que estaria bueno mover esos valores a compaion objet asi le agregamos algun nombre descriptivo como variables default.
> Capaz que podes usar algo asi Long.MIN_VALUE y MAX_VALUE

resuelto en default min,max constante

2020-11-12 13:06 UTC, snti commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +        return convertStringToDate(SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().time),"dd/MM/yyyy" )
Estaria bueno pasar el string format a una constante.

2020-11-12 13:08 UTC, snti commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +    /**
Se podra agregar un salto de linea entre cada metodo y el javadoc del metedo que le sigue abajo?

2020-11-12 13:14 UTC, snti commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +    /**
agregar salto de linea

2020-11-12 13:18 UTC, snti commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +    fun setupMinDate(minDate : String, format:String){
format:String necesita un espacio antes y despues del :

2020-11-12 13:22 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +        return convertStringToDate(SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().time),"dd/MM/yyyy" )
Resuelto en "saltos de linea y format a const"

2020-11-12 13:22 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +    /**
Resuelto en "saltos de linea y format a const"

2020-11-12 13:22 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +    /**
Resuelto en "saltos de linea y format a const"

2020-11-12 13:26 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +    fun setupMinDate(minDate : String, format:String){
Resuelto en "espacios entre :"

2020-11-12 14:02 UTC, snti commented on demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/DatePickerShowcaseActivity.kt
> +                    datepicker.setupMaxDate(setterMax, "dd/MM/yyyy" )
que sucede si un dev no valida la fecha y se la pasa directamente al setupMaxDate?

2020-11-12 14:04 UTC, snti commented on demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/DatePickerShowcaseActivity.kt
> +                datepicker.clearMinMaxDate()
el dev siempre tendria q ejecutar este metodo antes de setear el rango de fechas? no se podra de alguna forma manejar esa logica del lado del componente?

2020-11-12 14:20 UTC, snti commented on demoapp/src/main/res/values/strings.xml
> +
se podran quitar estos espacios?

2020-11-12 14:31 UTC, AdrianDeSeta1985 commented on demoapp/src/main/res/values/strings.xml
> +
resuelto "validate date in component, strings fix"

2020-11-12 14:32 UTC, AdrianDeSeta1985 commented on demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/DatePickerShowcaseActivity.kt
> +                    datepicker.setupMaxDate(setterMax, "dd/MM/yyyy" )
resuelto "validate date in component, strings fix"

2020-11-12 15:00 UTC, AdrianDeSeta1985 commented on demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/DatePickerShowcaseActivity.kt
> +                datepicker.clearMinMaxDate()
resuelto en reset min max , component

2020-11-19 15:19 UTC, barriosnahuel requested changes

2020-11-19 15:19 UTC, barriosnahuel commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +import java.util.*
en general es buena convención no usar el * para los import, los ponemos explícitamente por favor?

2020-11-19 15:19 UTC, barriosnahuel commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +@Suppress("TooManyFunctions")
podemos refactorear el componente para que no tener que suprimir el warning?

2020-11-19 15:19 UTC, barriosnahuel commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +    @Suppress("NULLABILITY_MISMATCH_BASED_ON_JAVA_ANNOTATIONS")
agregamos documentacion aclarando por qué estamos suprimiendo los warnings por favor?

2020-11-19 15:19 UTC, barriosnahuel commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +            }else{
veo qeu esta sin formato esto, te corres el formatter dede el IDE por favor?

2020-11-19 15:19 UTC, barriosnahuel commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +                Toast.makeText(context, "la fecha minima tiene que ser mayor o igual a la fecha actual", Toast.LENGTH_SHORT).show()
esto lo tenemos queborrar, no?

2020-11-19 15:19 UTC, barriosnahuel commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +                Toast.makeText(context, "la fecha maxima tiene que ser mayor a la fecha minima y mayor a la fecha actual", Toast.LENGTH_SHORT).show()
idem

2020-11-19 15:19 UTC, barriosnahuel commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +    fun setupMaxDate(maxDate : String, format : String){
deje unos comentarios en el RFC sobre estos métodos, lo revisamos por las dudas antes de seguir codeandolo?

2020-11-19 15:19 UTC, barriosnahuel commented on components/src/main/res/values/dimens_text.xml
> +    <dimen name="andes_body_font_size_xxs">10dp</dimen>
este tamaño no está definido en Andes, validamos por las dudas con UX que sea válido?
![image](https://user-images.githubusercontent.com/196234/99685526-72bb3d80-2a61-11eb-8199-27d53db5be65.png)

2020-11-19 15:45 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +import java.util.*
resuelto en "remove imports y setup Date"

2020-11-19 15:50 UTC, AdrianDeSeta1985 commented on components/src/main/res/values/dimens_text.xml
> +    <dimen name="andes_body_font_size_xxs">10dp</dimen>
ok lo agregue por que en el zeplin figura 10sp

2020-11-19 16:42 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +            }else{
resuelto en "fotmat code"

2020-11-19 16:52 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +                Toast.makeText(context, "la fecha minima tiene que ser mayor o igual a la fecha actual", Toast.LENGTH_SHORT).show()
resuelto en "remove toast"

2020-11-19 16:52 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +                Toast.makeText(context, "la fecha maxima tiene que ser mayor a la fecha minima y mayor a la fecha actual", Toast.LENGTH_SHORT).show()
resuelto en "remove toast"

2020-11-19 17:14 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +    fun setupMaxDate(maxDate : String, format : String){
resuelto en "refactor set min max only long"

2020-11-19 18:18 UTC, AdrianDeSeta1985 commented on components/src/main/res/values/dimens_text.xml
> +    <dimen name="andes_body_font_size_xxs">10dp</dimen>
resuelto en "calendar font size 2"

2020-11-19 18:31 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +    @Suppress("NULLABILITY_MISMATCH_BASED_ON_JAVA_ANNOTATIONS")
ya fueron retirados

2020-11-19 21:04 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +@Suppress("TooManyFunctions")
realize refactor y no pude quitar nada mas.

2020-11-19 21:33 UTC, barriosnahuel commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +            text: String? = TEXT_DEFAULT,
vale la pena tener esta constante? no podemos dejarle el null y listo?

2020-11-19 21:33 UTC, barriosnahuel commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +import kotlinx.android.synthetic.main.andes_layout_datepicker.view.andesBtnSelectDate
podemos cambiar el uso de synthetic accesors por otra cosa? hace un tiempo avisaron que tiene problemas de performance y no es buena práctica usarlo: https://old.reddit.com/r/androiddev/comments/ala9p2/why_kotlinx_synthetic_is_no_longer_a_recommended/efdvpkg/

2020-11-20 12:58 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +            text: String? = TEXT_DEFAULT,
se resolvio en "se removio la constante TEXT_DEFAULT"

2020-11-20 13:01 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +import kotlinx.android.synthetic.main.andes_layout_datepicker.view.andesBtnSelectDate
resuelto en "synthetic accesors remove"

2020-11-20 13:42 UTC, barriosnahuel commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +
```suggestion
/**
 * Warning TooManyFunctions suppressed because of...
 */ 
```

2020-11-20 13:47 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +
resuelto en "mensaje de or que esta suprimido el TooManyFunctions"

2020-11-20 15:31 UTC, barriosnahuel commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +        var cumple: Boolean = true
cumple (?)

2020-11-20 15:31 UTC, barriosnahuel commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +            cumple = minDateDate.time < calendarView.maxDate
lo ponemos en inglés?

2020-11-20 15:31 UTC, barriosnahuel commented on components/src/main/res/datepicker/values/dimens_datepicker.xml
> +    <dimen name="andes_datepicker_week_font_size">10dp</dimen>
el tamaño de la fuente es buen apráctica hacerlo en SP, lo podremos cambiar?

2020-11-20 15:46 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> + * no se pudo reducir el total de funciones a 11, ya que son todas necesarias para el seteo y validacion del componente
resuelto en "javadoc en ingles"

2020-11-20 15:51 UTC, AdrianDeSeta1985 commented on components/src/main/res/datepicker/values/dimens_datepicker.xml
> +    <dimen name="andes_datepicker_week_font_size">10dp</dimen>
resuelto en "cambio de funciones a ingles, dp a sp"

2020-11-20 15:51 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +            cumple = minDateDate.time < calendarView.maxDate
resuelto en "cambio de funciones a ingles, dp a sp"

2020-11-20 15:51 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +        var cumple: Boolean = true
resuelto en "cambio de funciones a ingles, dp a sp"

2020-11-24 18:15 UTC, RodriP commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +        if (id == NO_ID) { // If this view has no id
Esto es un stirng? no se compararía con == si es el caso, usaría un equals y primero siempre validaría con la constante NO_ID.equals..

2020-11-24 18:15 UTC, RodriP commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +        calendarView.minDate = DEFAULT_MIN_DATE
DEFAULT_MIN_DATE no debería ser el default si no nos pasan datos en el constructor?

2020-11-24 18:15 UTC, RodriP commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +    private fun setMinDate(minDate: Long) {
Le agregaria javadoc :)

2020-11-24 18:15 UTC, RodriP commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +        if (calendarView.maxDate != null) {
que pasa si es null?

2020-11-24 18:15 UTC, RodriP commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +        if (validateDateToCurrentDate(minDateDate) == 0) {
No me queda claro este flujo, pregunta por varias validaciones pero siempre termina haciendo : 
```
            calendarView.minDate = minDate
```
No se puede reordenar para juntar las condiciones y hacer esto una sola vez?

2020-11-24 18:15 UTC, RodriP commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +        calendarView.maxDate = DEFAULT_MAX_DATE
Se puede usar como Default si no nos pasan nada en el constructor?

2020-11-24 18:15 UTC, RodriP commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +        if (calendarView.minDate != null) {
Que pasa si es null?

2020-11-24 18:15 UTC, RodriP commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +            calendarView.maxDate = maxDate
Aca es lo mismo, preguntamos por diferentes validaciones que siempre terminan en             calendarView.maxDate = maxDate

2020-11-24 18:15 UTC, RodriP commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +    private fun onCheckedChangeListener(andesBtnSelectDate: AndesButton) {
le agregamos javadoc? :)

2020-11-24 18:15 UTC, RodriP commented on components/src/main/res/layout/andes_layout_datepicker.xml
> +        android:layout_marginTop="24dp"/>
Lo pasamos a una dim?

2020-11-24 18:15 UTC, RodriP commented on components/src/test/java/com/mercadolibre/android/andesui/datepicker/AndesDatePickerTest.kt
> +class AndesDatePickerTest{
Que pasa si le pasamos todo null como hoy se esta aceptando? podemos testear ese caso?

2020-11-24 18:15 UTC, RodriP commented on components/src/test/java/com/mercadolibre/android/andesui/datepicker/AndesDatePickerTest.kt
> +class AndesDatePickerTest{
Por eso mencionaba si deberiamos manejar casos por default y testear eso justamente

2020-11-24 18:15 UTC, RodriP commented on demoapp/src/main/res/raw/andesui_demoapp_changelog.md
> +## 🚀 Features
Recordar apuntar a la siguiente version, esta ya salio

2020-11-24 18:56 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +            context: Context,
resuelto en "@Dimen, valores defalt , javadocs"

2020-11-24 18:57 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +        calendarView.minDate = DEFAULT_MIN_DATE
resuelto en "@Dimen, valores defalt , javadocs"

2020-11-24 18:57 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +    private fun setMinDate(minDate: Long) {
resuelto en "@Dimen, valores defalt , javadocs"

2020-11-24 18:57 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +    private fun onCheckedChangeListener(andesBtnSelectDate: AndesButton) {
resuelto en "@Dimen, valores defalt , javadocs"

2020-11-24 18:57 UTC, AdrianDeSeta1985 commented on components/src/main/res/layout/andes_layout_datepicker.xml
> +        android:layout_marginTop="24dp"/>
resuelto en "@Dimen, valores defalt , javadocs"

2020-11-24 18:59 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +        if (id == NO_ID) { // If this view has no id
esto se autogenero con el componente, vi que estaba igual en todos lados y lo deje asi.

2020-11-24 19:04 UTC, RodriP commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +        if (id == NO_ID) { // If this view has no id
@jperezgonzal tincho capaz hay que mirar el template, si es un string la comparacion no deberia ser ==

2020-11-24 19:16 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +            calendarView.maxDate = maxDate
resuelto en "refactor setupMin, setupMax date"

2020-11-24 19:16 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +        if (calendarView.maxDate != null) {
resuelto en "refactor setupMin, setupMax date"

2020-11-24 19:17 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +        if (validateDateToCurrentDate(minDateDate) == 0) {
resuelto en "refactor setupMin, setupMax date"

2020-11-24 19:17 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +        if (calendarView.minDate != null) {
resuelto en "refactor setupMin, setupMax date"

2020-11-24 19:26 UTC, AdrianDeSeta1985 commented on components/src/test/java/com/mercadolibre/android/andesui/datepicker/AndesDatePickerTest.kt
> +class AndesDatePickerTest{
resuelto en refactor "setupMin, setupMax date"

2020-11-24 19:36 UTC, AdrianDeSeta1985 commented on CHANGELOG.md
> +## 🚀 Features
resuelto en "changelog +1"

2020-11-24 19:36 UTC, AdrianDeSeta1985 commented on demoapp/src/main/res/raw/andesui_demoapp_changelog.md
> +## 🚀 Features
resuelto en "changelog +1"

2020-11-24 19:36 UTC, AdrianDeSeta1985 commented on components/src/main/java/com/mercadolibre/android/andesui/datepicker/AndesDatePicker.kt
> +        calendarView.maxDate = DEFAULT_MAX_DATE
resuelto en "refactor setupMin, setupMax date"

2020-11-24 19:39 UTC, RodriP approved these changes

2020-11-24 19:42 UTC, snti approved these changes

2020-11-24 21:23 UTC, barriosnahuel approved these changes
gracias @AdrianDeSeta1985!!

2020-11-25 13:34 UTC, merged