Feature/andes dropdown
mercadolibre/fury_andesui-android pull request #207
Opened 2020-12-28 15:44 UTC by snti

### Thanks for starting a pull request on Andes UI!

## Useful links
- [Contributing](https://github.com/mercadolibre/fury_andesui-android/blob/develop/CONTRIBUTING.md) has more information and tips for a great pull request. This will give you a nice introduction about how to contribute with Andes.
- [Wiki](https://github.com/mercadolibre/fury_andesui-android/wiki) has all the info you need to start with Andes. Even I heard there's a video there...

## Motivation
Tell us why you are here and why you took time to develop new code for our beloved lib.

## Description
Please describe your intentions with this new code you want to introduce inside Andes UI lib.
Try to answer those questions:
- What is it about?
- How does it work?

## Affected component
Is highly probable that this new code directly affects one (or more?) components inside this lib. Tell us who they are!

## Frontify component link
The UX team behind Andes keeps all the Andes Components inside the Frontify site. Each component has its own section. Let us know the section of the component you want to modify.

## Screenshots
This is a UI library, delight us with some stunning images.

## Checks
Are you sure you followed all those steps? In such case, let's say with me "I solemnly declare that ...":
- [ ] I have coded an example inside the Demo App,
- [ ] I have added proper tests,
- [ ] I have modified the [Changelog](https://github.com/mercadolibre/fury_andesui-android/blob/develop/CHANGELOG.md) file,
- [ ] I have updated GitHub wiki,
- [ ] I have the explicit approval of one or more members of the UX Team,
- [ ] I have updated the version in gradle.properties file.

## Change type
This is easy, let us know what this code is about:
- [ ] This code adds a new component
- [ ] This code includes improvements to an existent component
- [ ] This code improves or modifies ONLY the Demo App.

## Check common errors
Whether you are an Android or iOS developer and if you're still there then we'll give you a present:
https://proandroiddev.com/how-to-maximize-androids-ui-reusability-5-common-mistakes-cb2571216a9f

2020-12-30 16:24 UTC, jperezgonzal requested changes
Arreglaría un poco la demoapp. 
- Utilizaría los componentes de Andes en lugar del EditText (en title y placeholder) 
- Agregaría mas separación entre los botones y el input de arriba
- Las constraint de los botones las haría igual que el resto de los components (creo que el update está con 0dp)
- Capaz agregar un AndesMessage arriba de todo (como los otros componentes) con un mensaje de cuando se debería utilizar ese componente. (Eso lo sacabamos de Frontify)

2020-12-30 16:24 UTC, jperezgonzal commented on components/src/main/java/com/mercadolibre/android/andesui/dropdown/AndesDropdownStandalone.kt
> +            andesDropdownAttrs = andesDropdownAttrs.copy(andesDropdownMenuType = value)
Que pasa si actualizan esto en tiempo de ejecución? Debería actualizarse, lanzar un warning, o una excepción?

2020-12-30 16:24 UTC, jperezgonzal commented on components/src/main/java/com/mercadolibre/android/andesui/dropdown/size/AndesDropdownSize.kt
> +    private fun getAndesListRowSize(): AndesDropdownSizeInterface {
Renombrar getAndesListRowSize

2020-12-30 16:24 UTC, jperezgonzal commented on components/src/main/java/com/mercadolibre/android/andesui/dropdown/type/AndesDropdownMenu.kt
> +    override fun getType(context: Context) = AndesDropdownMenuType.BOTTOMSHEET
Porque se le está pasando el **context** aca?

2020-12-30 16:24 UTC, jperezgonzal commented on components/src/main/java/com/mercadolibre/android/andesui/dropdown/type/AndesDropdownMenu.kt
> +    override fun getType(context: Context) = AndesDropdownMenuType.FLOATINGMENU
Porque se le está pasando el **context** aca?

2020-12-30 16:24 UTC, jperezgonzal commented on components/src/main/res/layout/andes_layout_dropdown_bottom_sheet.xml
> +    <LinearLayout
Utilizar ConstraintLayouts

2020-12-30 16:24 UTC, jperezgonzal commented on components/src/main/res/layout/andes_layout_dropdown_bottom_sheet.xml
> +    <LinearLayout
Se puede hacer en un nivel sólo?

2020-12-30 17:19 UTC, snti commented on components/src/main/res/layout/andes_layout_dropdown_bottom_sheet.xml
> +    <LinearLayout
Entiendo que ConstraintLayout este mejor optimizado que el RelativeLayout, pero tambien que linearlayout?

2020-12-30 18:12 UTC, jperezgonzal commented on components/src/main/res/layout/andes_layout_dropdown_bottom_sheet.xml
> +    <LinearLayout
Si, ConstraintLayout sin duda es mejor que RelativeLayout, y con LinearLayout depende de la complejidad de la pantalla (esto respecto al tiempo en el que demora en renderizar esa pantalla). 
De todas formas, generalmente con ConstraintLayout se tienen mejoras de overdraw. Y por otra parte, con ConstraintLayout capaz que se puede hacer esa misma pantalla con un solo nivel de anidamiento, y cuanto menos tengamos más rápido es tiempo en que renderiza la pantalla

2021-01-08 22:06 UTC, jperezgonzal submitted a review, later dismissed

2021-01-11 15:35 UTC, barriosnahuel approved these changes

2021-01-11 15:39 UTC, barriosnahuel approved these changes

2021-01-11 15:42 UTC, merged