Feature feedback in app component
mercadolibre/fury_andesui-android pull request #208
Opened 2020-12-28 17:34 UTC by Dzavala-dev

### Thanks for starting a pull request on Andes UI!

## Useful links
- [Contributing](https://github.com/mercadolibre/fury_andesui-android/blob/develop/CONTRIBUTING.md) has more information and tips for a great pull request. This will give you a nice introduction about how to contribute with Andes.
- [Wiki](https://github.com/mercadolibre/fury_andesui-android/wiki) has all the info you need to start with Andes. Even I heard there's a video there...

## Motivation
Tell us why you are here and why you took time to develop new code for our beloved lib.

Im helping with create a new component called "Feedback In App"

## Description
Please describe your intentions with this new code you want to introduce inside Andes UI lib.
Try to answer those questions:
- What is it about? It's a component thats just redirect the user to a CB
- How does it work? When a user need to tell us or give us point about the item or anything on the platform just need to click on "ayudanos a mejorar" 

## Affected component
Is highly probable that this new code directly affects one (or more?) components inside this lib. Tell us who they are!

## Frontify component link
The UX team behind Andes keeps all the Andes Components inside the Frontify site. Each component has its own section. Let us know the section of the component you want to modify.

## Screenshots
<img width="306" alt="Captura de Pantalla 2020-12-28 a la(s) 11 21 43" src="https://user-images.githubusercontent.com/64223132/103231978-deb18100-48fe-11eb-9a54-450092cccdaf.png">

## Checks
Are you sure you followed all those steps? In such case, let's say with me "I solemnly declare that ...":
- [X] I have coded an example inside the Demo App,
- [ ] I have added proper tests,
- [ ] I have modified the [Changelog](https://github.com/mercadolibre/fury_andesui-android/blob/develop/CHANGELOG.md) file,
- [X] I have updated GitHub wiki,
- [ ] I have the explicit approval of one or more members of the UX Team,
- [ ] I have updated the version in gradle.properties file.

## Change type
This is easy, let us know what this code is about:
- [X] This code adds a new component
- [ ] This code includes improvements to an existent component
- [ ] This code improves or modifies ONLY the Demo App.

## Check common errors
Whether you are an Android or iOS developer and if you're still there then we'll give you a present:
https://proandroiddev.com/how-to-maximize-androids-ui-reusability-5-common-mistakes-cb2571216a9f

2020-12-28 18:09 UTC, mauriciogigena requested changes

2020-12-28 18:09 UTC, mauriciogigena commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +@Suppress("TooManyFunctions")
si no te marca este warning no hace falta que agregues el suppress

2020-12-28 18:09 UTC, mauriciogigena commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +
aca te quedo un enter de mas

2020-12-28 18:09 UTC, mauriciogigena commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +    private fun setupBodyComponent(config: FeedbackInAppConfiguration) {
el metodo deberia referirse al text o message, no a body

2020-12-28 18:09 UTC, mauriciogigena commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +    private fun setupBodyComponent(config: FeedbackInAppConfiguration) {
ademas te quedo un salto de linea

2020-12-28 18:09 UTC, mauriciogigena commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +
saltos de linea

2020-12-28 18:09 UTC, mauriciogigena commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/factory/FeedbackInAppAttrsParser.kt
> +    private const val ANDES_FeedbackInApp_HIERARCHY_LOUD = "100"
estos lo usamos en el componente feeback in app? no tiene hierarchy

2020-12-28 18:09 UTC, mauriciogigena commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/factory/FeedbackInAppConfigurationFactory.kt
> +
salto de linea

2020-12-28 18:09 UTC, mauriciogigena commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/hierarchy/AndesFeedbackInAppHierarchy.kt
> +enum class AndesFeedbackInAppHierarchy {
no tiene hierarchies el componente

2020-12-28 18:09 UTC, mauriciogigena commented on components/src/main/res/layout/andes_layout_feedbackinapp.xml
> +            android:textColor="#73000000"
esto deberia estr en colors file

2020-12-28 18:09 UTC, mauriciogigena commented on components/src/main/res/layout/andes_layout_feedbackinapp.xml
> +            android:layout_height="32dp"
las medidas en dimens

2020-12-28 18:13 UTC, Dzavala-dev commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +@Suppress("TooManyFunctions")
Remuevo todos los "@Suppress"??

2020-12-28 18:14 UTC, mauriciogigena commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +@Suppress("TooManyFunctions")
solo este por ahora

2020-12-28 18:20 UTC, Dzavala-dev commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/hierarchy/AndesFeedbackInAppHierarchy.kt
> +enum class AndesFeedbackInAppHierarchy {
Listo ya se borro el Hierarchy

2020-12-28 18:20 UTC, Dzavala-dev commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/factory/FeedbackInAppAttrsParser.kt
> +    private const val ANDES_FeedbackInApp_HIERARCHY_LOUD = "100"
Listo ya se borro el Hierarchy

2020-12-28 18:21 UTC, Dzavala-dev commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +    private fun setupBodyComponent(config: FeedbackInAppConfiguration) {
ya se modigico a setupMessageComponent

2020-12-28 18:34 UTC, Dzavala-dev commented on components/src/main/res/layout/andes_layout_feedbackinapp.xml
> +            android:layout_height="32dp"
Listo ya se agregaron 
![Captura de Pantalla 2020-12-28 a la(s) 12 34 11](https://user-images.githubusercontent.com/64223132/103235957-01489780-4909-11eb-9888-c8d679e97723.png)

2020-12-28 18:35 UTC, Dzavala-dev commented on components/src/main/res/layout/andes_layout_feedbackinapp.xml
> +            android:textColor="#73000000"
Listo

![Captura de Pantalla 2020-12-28 a la(s) 12 34 47](https://user-images.githubusercontent.com/64223132/103235992-1de4cf80-4909-11eb-88bb-077c608b2fdf.png)

2021-01-06 13:14 UTC, mzangl-meli commented on components/src/main/res/layout/andes_layout_feedbackinapp.xml
> +            android:layout_marginTop="15dp"
use dimen

2021-01-06 13:25 UTC, mauriciogigena requested changes

2021-01-06 13:25 UTC, mauriciogigena commented on components/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
por que se importa esto?

2021-01-06 13:25 UTC, mauriciogigena commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +@Suppress("TooManyFunctions")
este quedo, habia que sacarlo

2021-01-06 13:25 UTC, mauriciogigena commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +    private lateinit var feedbackdivider: View
Divider, con D

2021-01-06 13:25 UTC, mauriciogigena commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +           setupcardBackground(createConfig())
Card con C

2021-01-06 13:25 UTC, mauriciogigena commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +    @Suppress("unused", "LongParameterList")
Este no deberia hacer falta, borrarlo y fijate si te marca algo

2021-01-06 13:25 UTC, mauriciogigena commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +    @Suppress("LongParameterList")
Este no deberia hacer falta, borrarlo y fijate si te marca algo

2021-01-06 13:25 UTC, mauriciogigena commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +        feedbackinappMessage = container.findViewById(R.id.andes_descriptionText)
Aca todo se viene llamando "andes_feedback_algo y este es andes_descriptionText, incluso esta escrito de manera diferente

2021-01-06 13:25 UTC, mauriciogigena commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +            feedbackdivider.visibility = View.VISIBLE
no es un error, pero View deberia estar en los imports

2021-01-06 13:25 UTC, mauriciogigena commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +            this.setBackgroundColor(ContextCompat.getColor(context, R.color.andes_bg_color_white))
el color por defecto deberia ser un gray

2021-01-06 13:25 UTC, mauriciogigena commented on components/src/main/res/layout/andes_layout_feedbackinapp.xml
> +            tools:layout_editor_absoluteX="16dp" />
esto deberia estar en dimens

2021-01-06 13:25 UTC, mauriciogigena commented on components/src/main/res/layout/andes_layout_feedbackinapp.xml
> +            android:layout_marginTop="15dp"
dimens, y ademas me parece que esta mal el numero, siempre usamos pares, revisaloo en zeplin

2021-01-06 13:25 UTC, mauriciogigena commented on components/src/main/res/values/dimens_feedbackinapp.xml
> +    <dimen name="andes_feedback_textmarginBottom">17dp</dimen>
revisa estos valores con zeplin

2021-01-06 16:27 UTC, Dzavala-dev commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +@Suppress("TooManyFunctions")
Si lo saque, pero me pone warning y no pasa el PR , por eso lo volvi a poner ayer @mauriciogigena

2021-01-06 19:23 UTC, mdobratinich requested changes

2021-01-06 19:23 UTC, mdobratinich commented on components/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
Si hay que sacar ese import

2021-01-06 19:23 UTC, mdobratinich commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +           setupcardBackground(createConfig())
+1

2021-01-06 19:23 UTC, mdobratinich commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +
Esta linea esta de mas

2021-01-06 19:23 UTC, mdobratinich commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +        if (config.cardText == null || config.cardText.isEmpty()) {
Queda mas prolijo usar:
`config.cardText.isNullOrEmpty()`

2021-01-06 19:23 UTC, mdobratinich commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +            if (config.action == null || config.action.isEmpty()) {
idem anterior

2021-01-06 19:23 UTC, mdobratinich commented on components/src/main/res/layout/andes_layout_feedbackinapp.xml
> +        android:layout_height="130dp"
mover a dimen

2021-01-06 19:23 UTC, mdobratinich commented on components/src/test/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInAppTest.kt
> +                buttonLabel = "Ayuda a mejorar",
Los string pasalos a constantes o usa los String declarados en el String.xml

2021-01-06 19:23 UTC, mdobratinich commented on components/src/test/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInAppTest.kt
> +                cardBackgroundColor = "#FF7733"
Usa un AndesColor

2021-01-06 19:23 UTC, mdobratinich commented on demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/FeedbackInAppActivity.kt
> +import android.widget.*
evita usar wildcards

2021-01-06 19:23 UTC, mdobratinich commented on demoapp/src/main/res/layout/andesui_feedbackinapp_change.xml
> +                android:layout_marginTop="15dp"
mover a dimen

2021-01-06 19:23 UTC, mdobratinich commented on demoapp/src/main/res/layout/andesui_feedbackinapp_change.xml
> +                android:layout_width="390dp"
mover a dimen

2021-01-06 19:23 UTC, mdobratinich commented on demoapp/src/main/res/layout/andesui_feedbackinapp_change.xml
> +                android:layout_marginBottom="10dp"
idem

2021-01-06 19:23 UTC, mdobratinich commented on demoapp/src/main/res/layout/andesui_feedbackinapp_change.xml
> +                android:layout_marginBottom="10dp"
idem

2021-01-06 19:23 UTC, mdobratinich commented on demoapp/src/main/res/layout/andesui_feedbackinapp_change.xml
> +            android:layout_height="37dp"
idem

2021-01-06 19:23 UTC, mdobratinich commented on demoapp/src/main/res/layout/andesui_feedbackinapp_change.xml
> +            android:layout_height="37dp"
idem

2021-01-07 13:48 UTC, mdobratinich commented on components/src/main/res/layout/andes_layout_feedbackinapp.xml
> +            android:id="@+id/andes_feedbackinapp_cardText"
Los ids no deben tener camel case... andes_feedbackinapp_card_text

2021-01-07 13:48 UTC, mdobratinich commented on components/src/main/res/layout/andes_layout_feedbackinapp.xml
> +            android:layout_marginBottom="@dimen/andes_feedback_textmarginBottom"
igual que el comentario anterior

2021-01-07 13:48 UTC, mdobratinich commented on components/src/main/res/layout/andes_layout_feedbackinapp.xml
>              android:layout_marginBottom="@dimen/andes_feedback_marginBottom"
igual que el comentario anterior

2021-01-07 13:48 UTC, mdobratinich commented on components/src/main/res/layout/andes_layout_feedbackinapp.xml
> +            app:layout_constraintTop_toBottomOf="@+id/andes_feedbackinapp_cardText" />
igual que el comentario anterior

2021-01-08 20:16 UTC, mauriciogigena requested changes

2021-01-08 20:16 UTC, mauriciogigena commented on demoapp/build.gradle
> +    implementation 'com.android.support:support-v4:28.0.0'
esto no deberia estar, salvo que se haya agregado con un pull de develop.

2021-01-08 20:35 UTC, mdobratinich commented on components/src/main/java/com/mercadolibre/android/andesui/feedbackinapp/AndesFeedbackInApp.kt
> +        }
Cambia la logica de 3 if por un when
```suggestion
        when(config.cardTextAlignment) {
               AndesFeedbackInAppAlign.LEFT -> feedbackinappMessage.gravity = Gravity.LEFT
               AndesFeedbackInAppAlign. RIGHT -> feedbackinappMessage.gravity = Gravity. RIGHT
               else -> feedbackinappMessage.gravity = Gravity.CENTER
        }
```

2021-01-08 20:43 UTC, mdobratinich commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip
Estos cambios no creo que sean necesarios.. revisalo, sino reverti estos cambios

2021-01-14 21:46 UTC, closed without merging