AndesButton with drawable support
mercadolibre/fury_andesui-android pull request #225
Opened 2021-01-20 13:19 UTC by a0zamora

## Description
This new feature allows the user to set a Drawable programmatically.

## Affected component
AndesButton

## Screenshots
![2021-01-19 16 22 54](https://user-images.githubusercontent.com/13289298/105180120-eaacef00-5b08-11eb-8b13-c6e87fdfea1e.gif)

## Checks
Are you sure you followed all those steps? In such case, let's say with me "I solemnly declare that ...":
- [x] I have coded an example inside the Demo App,
- [x] I have added proper tests,
- [ ] I have modified the [Changelog](https://github.com/mercadolibre/fury_andesui-android/blob/develop/CHANGELOG.md) file,
- [ ] I have updated GitHub wiki,
- [ ] I have the explicit approval of one or more members of the UX Team,
- [ ] I have updated the version in gradle.properties file.

## Change type
This is easy, let us know what this code is about:
- [ ] This code adds a new component
- [x] This code includes improvements to an existent component
- [ ] This code improves or modifies ONLY the Demo App.

2021-01-20 14:24 UTC, cvillamilmeli requested changes
Please review some comments

2021-01-20 14:24 UTC, cvillamilmeli commented on components/src/main/java/com/mercadolibre/android/andesui/button/size/AndesButtonSizeInterface.kt
> +    private fun handleStringIcon(context: Context, leftIcon: String,
Please change this name, because is not a String icon, is the path of the icon.
```suggestion
    private fun handlePathIcon(context: Context, iconPath: String,
```

2021-01-20 14:24 UTC, cvillamilmeli commented on demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/ButtonShowcaseActivity.kt
> +                ResourcesCompat.getDrawable(resources, R.drawable.andesui_icon_dynamic, null)!!,
avoid use `!!`, please check another way to make that getDrawable don't get null or check before if the reference is `!= null` or use 
```
ResourcesCompat.getDrawable(resources, R.drawable.andesui_icon_dynamic, null)?.let{
.....
}
```

2021-01-20 14:24 UTC, cvillamilmeli commented on demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/ButtonShowcaseActivity.kt
> +                ResourcesCompat.getDrawable(resources, R.drawable.andesui_icon_dynamic, null)!!,
Same here about don't use `!!`

2021-01-20 14:24 UTC, cvillamilmeli commented on demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/ButtonShowcaseActivity.kt
> +                ResourcesCompat.getDrawable(resources, R.drawable.andesui_icon_dynamic, null)!!,
same here, please don't use `!!`

2021-01-20 14:24 UTC, cvillamilmeli commented on demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/ButtonShowcaseActivity.kt
> +                ResourcesCompat.getDrawable(resources, R.drawable.andesui_icon_dynamic, null)!!,
same here, please don't use `!!`

2021-01-20 14:24 UTC, cvillamilmeli commented on demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/ButtonShowcaseActivity.kt
> +                ResourcesCompat.getDrawable(resources, R.drawable.andesui_icon_dynamic, null)!!,
same here, please don't use `!!`

2021-01-20 14:24 UTC, cvillamilmeli commented on demoapp/src/main/java/com/mercadolibre/android/andesui/demoapp/feature/ButtonShowcaseActivity.kt
> +                ResourcesCompat.getDrawable(resources, R.drawable.andesui_icon_dynamic, null)!!,
same here, please don't use `!!`

2021-01-20 16:17 UTC, cvillamilmeli submitted a review, later dismissed

2021-01-20 19:40 UTC, cvillamilmeli approved these changes

2021-01-20 20:11 UTC, eportasML commented on components/src/main/java/com/mercadolibre/android/andesui/button/AndesButton.kt
> +    fun setIconDrawable(drawable: Drawable, orientation: AndesButtonIconOrientation) {
Agregamos javadoc a los metodos?

2021-01-20 20:12 UTC, eportasML commented on demoapp/src/main/res/raw/andesui_demoapp_changelog.md
> +
Borra esto :)

2021-01-20 20:12 UTC, eportasML commented on demoapp/src/main/res/raw/andesui_demoapp_changelog.md
>  # v3.5.1
Saquemos 3.5.1 y que quede todo bajo 3.6.0 que es la que saldra

2021-01-20 20:14 UTC, eportasML commented on CHANGELOG.md
>  # v3.5.1
Saquemos la linea de 3.5.1 porque va a salir como parte de la 3.6.0

2021-01-20 20:14 UTC, eportasML commented on CHANGELOG.md
> +### 🚀 Feature
son dos ##

2021-01-20 20:15 UTC, eportasML commented on components/src/main/java/com/mercadolibre/android/andesui/button/size/AndesButtonSizeInterface.kt
> +            rightDrawable != null -> { // Ignoring if rightIcon is also non null: Left icon has higher precedence than right
los comments estan mal

2021-01-20 20:16 UTC, eportasML commented on demoapp/src/main/res/raw/andesui_demoapp_changelog.md
> +### 🚀 Feature
Son dos ##

2021-01-21 14:51 UTC, eportasML approved these changes

2021-01-21 14:53 UTC, merged