Adding Walkthrough Scrolless
mercadolibre/fury_andesui-android pull request #229
Opened 2021-01-26 19:49 UTC by agusanchez

### Thanks for starting a pull request on Andes UI!

## Useful links
- [Contributing](https://github.com/mercadolibre/fury_andesui-android/blob/develop/CONTRIBUTING.md) has more information and tips for a great pull request. This will give you a nice introduction about how to contribute with Andes.
- [Wiki](https://github.com/mercadolibre/fury_andesui-android/wiki) has all the info you need to start with Andes. Even I heard there's a video there...

## Motivation
Tell us why you are here and why you took time to develop new code for our beloved lib.

## Description
Please describe your intentions with this new code you want to introduce inside Andes UI lib.
Try to answer those questions:
- What is it about?
- How does it work?

## Affected component
Is highly probable that this new code directly affects one (or more?) components inside this lib. Tell us who they are!

## Frontify component link
The UX team behind Andes keeps all the Andes Components inside the Frontify site. Each component has its own section. Let us know the section of the component you want to modify.

## Screenshots
This is a UI library, delight us with some stunning images.

## Checks
Are you sure you followed all those steps? In such case, let's say with me "I solemnly declare that ...":
- [ ] I have coded an example inside the Demo App,
- [ ] I have added proper tests,
- [ ] I have modified the [Changelog](https://github.com/mercadolibre/fury_andesui-android/blob/develop/CHANGELOG.md) file,
- [ ] I have updated GitHub wiki,
- [ ] I have the explicit approval of one or more members of the UX Team,
- [ ] I have updated the version in gradle.properties file.

## Change type
This is easy, let us know what this code is about:
- [ ] This code adds a new component
- [ ] This code includes improvements to an existent component
- [ ] This code improves or modifies ONLY the Demo App.

## Check common errors
Whether you are an Android or iOS developer and if you're still there then we'll give you a present:
https://proandroiddev.com/how-to-maximize-androids-ui-reusability-5-common-mistakes-cb2571216a9f

2021-02-05 16:59 UTC, cvillamilmeli commented
Puedes poner la Motivación y descripción, gracias

2021-02-05 17:16 UTC, cvillamilmeli requested changes
Buen trabajo, encontré unas opciones de mejora, las puedes revisar por favor?

2021-02-05 17:16 UTC, cvillamilmeli commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/presenter/CoachmarkPresenter.kt
>          stepReferenced.view.let {
```suggestion
        stepReferenced.view?.let {
```

Puedes hacer la validación de view? antes para que el it siempre sea != null, y evitar usar it!!

2021-02-05 17:16 UTC, cvillamilmeli commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/presenter/CoachmarkPresenter.kt
> +            if (isBodyMoreBottom || !it!!.getLocalVisibleRect(bodyGlobalRect) || bodyGlobalRect.height() < it!!.height) {
```suggestion
            if (isBodyMoreBottom || !it.getLocalVisibleRect(bodyGlobalRect) || bodyGlobalRect.height() < it.height) {
```

si previamente usamos el `view?.let{}` it ya es != null

2021-02-05 17:16 UTC, cvillamilmeli commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/model/AndesWalkthroughCoachmark.kt
> +        val view: View,
```suggestion
        val anchorView: View,
```
esta es la vista donde se ancla el walkthrough?

2021-02-05 17:16 UTC, cvillamilmeli commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/walkthroughscrolless/CoachmarkScrollessContainerView.kt
> +    fun setListener(l: CoachmarkContainerListener) {
```suggestion
    fun setListener(coachMarkContainerListener: CoachmarkContainerListener) {
```
evita nombres genéricos

2021-02-05 17:16 UTC, cvillamilmeli commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/walkthroughscrolless/CoachmarkScrollessContainerView.kt
> +    private var listener: CoachmarkContainerListener? = null
```suggestion
    private var coachMarkContainerListener: CoachmarkContainerListener? = null
```
evita nombres genéricos

2021-02-05 17:16 UTC, cvillamilmeli commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/walkthroughscrolless/WalkthroughScrollessMessageView.kt
> +        listener = l
evita nombres genéricos

2021-02-05 17:16 UTC, cvillamilmeli commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/walkthroughscrolless/WalkthroughScrollessMessageView.kt
> +        if (data.title.isNotEmpty()) {
create una función para encapsular la lógica de mostrar o no una vista dado un dato

```kotlin
fun checkViewVisibility(view: View, content: String) {
        view.visibility = if (content.isNotBlank()) {
            View.VISIBLE
        } else {
            View.GONE
        }
    }

2021-02-05 17:16 UTC, cvillamilmeli commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/walkthroughscrolless/WalkthroughScrollessMessageView.kt
> +        }
Todo esto se evita con el comentario de arriba

2021-02-05 17:16 UTC, cvillamilmeli commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/walkthroughscrolless/WalkthroughScrollessMessageView.kt
> +                arcArrowTop.visibility = View.VISIBLE
crea una función para encapsular toda la lógica una para BELOW y una para ABOVE

2021-02-05 17:16 UTC, cvillamilmeli commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/walkthroughscrolless/WalkthroughScrollessMessageView.kt
> +        } else if (centerTarget - centerTooltip >= 0 && centerTarget - centerTooltip <= minWithForShowArrow) {
encapsula cada una de las condiciones y evalúa si se puede usar un `||`

2021-02-05 17:16 UTC, cvillamilmeli commented on coachmark/src/main/res/layout/andes_walkthrough_scrolless_container.xml
> +        tools:ignore="ContentDescription"
por accesibilidad, no es bueno ignorar el content description

2021-02-05 18:03 UTC, eportasML commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/CoachmarkOverlay.kt
> -internal class CoachmarkOverlay @JvmOverloads constructor(
por que deja de ser internal?

2021-02-05 18:05 UTC, eportasML commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/CoachmarkView.kt
> +                    stepReferenced.view?.height ?: 0,
Por que `view` pasa a ser nulleable?

2021-02-05 18:06 UTC, eportasML commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/model/WalkthroughMessageModel.kt
> +    val buttonText: String = ""
Por que ""? No podria ser String?

2021-02-05 18:21 UTC, eportasML commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/walkthroughscrolless/CoachmarkScrollessContainerView.kt
> +class CoachmarkScrollessContainerView @JvmOverloads constructor(
Este scrolles containerView  se crea por alguna otra diferencia con `CoachmarkContainerView` ademas del layout?

2021-02-05 18:23 UTC, eportasML commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/walkthroughscrolless/CoachmarkScrollessView.kt
> +class CoachmarkScrollessView private constructor(builder: Builder) : CoachmarkViewInterface {
Que diferencia hay con `CoachmarkView`? no hay manera alguna de reusar código?

2021-02-05 18:29 UTC, eportasML commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/walkthroughscrolless/WalkthroughScrollessMessageView.kt
> +class WalkthroughScrollessMessageView @JvmOverloads constructor(
No hay manera de reusar codeigo de WalkthroughMessageView?

2021-02-05 19:52 UTC, agusanchez commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/model/AndesWalkthroughCoachmark.kt
> +        val view: View,
Si, exactamente! Le cambio el nombre para que sea mas descriptivo.

2021-02-05 20:15 UTC, agusanchez commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/CoachmarkOverlay.kt
> -internal class CoachmarkOverlay @JvmOverloads constructor(
Ahi volvi atras este cambio!

2021-02-05 20:19 UTC, agusanchez commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/CoachmarkView.kt
> +                    stepReferenced.view?.height ?: 0,
Porque si le pasas una view que es null dentro de la lista de Steps, la app termina en crash porque siempre espera una vista no nula. Si bien estamos chequeando que en la lista de steps no mandemos una vista vacia, prefiero que el walkthrough tambien tenga este chequeo. Ademas en la clase `CoachmarkScrollessView` recorremos los steps y eliminamos los que esten con su vista en null.

2021-02-05 20:20 UTC, agusanchez commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/model/WalkthroughMessageModel.kt
> +    val buttonText: String = ""
Sii, ahora lo cambio!

2021-02-05 20:22 UTC, agusanchez commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/walkthroughscrolless/CoachmarkScrollessContainerView.kt
> +class CoachmarkScrollessContainerView @JvmOverloads constructor(
Ademas de que el layout cambia, unos metodos que el original no tiene como: `getHeaderView` y `getCloseButtonView`

2021-02-05 20:25 UTC, agusanchez commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/walkthroughscrolless/CoachmarkScrollessView.kt
> +class CoachmarkScrollessView private constructor(builder: Builder) : CoachmarkViewInterface {
Hay varios cambios con respecto al primero que se creo, es por eso que para no romper la funcionalidad del actual y no  romper firma decidimos que era mejor crear uno nuevo.

2021-02-05 20:28 UTC, agusanchez commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/walkthroughscrolless/WalkthroughScrollessMessageView.kt
> +class WalkthroughScrollessMessageView @JvmOverloads constructor(
Esto es algo parecido a lo que te comentaba mas arriba, cambian algunas cosas en el layout y metodos de la clase. Por lo que la distinción entre uno y otro se hace mas compleja si mantenemos una sola clase.

2021-02-08 13:32 UTC, agusanchez commented
@eportasML @cvillamilmeli Les queria comentar que ya quedaron los cambios en el PR.

2021-02-08 20:11 UTC, agusanchez commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/model/WalkthroughMessageModel.kt
> +    val buttonText: String = ""
Finalmente no impacte este cambio, a raiz de que utilizamos el constructor con solo los dos primeros parametros. Que asi es como lo utiliza el primer Walkthrough. De esta manera no tuvimos que replicar el Model.

2021-02-08 20:54 UTC, jperezgonzal approved these changes

2021-02-08 20:57 UTC, cvillamilmeli approved these changes

2021-02-08 20:59 UTC, merged