Changing walkthrough design
mercadolibre/fury_andesui-android pull request #230
Opened 2021-01-26 19:53 UTC by agusanchez

### Thanks for starting a pull request on Andes UI!

## Useful links
- [Contributing](https://github.com/mercadolibre/fury_andesui-android/blob/develop/CONTRIBUTING.md) has more information and tips for a great pull request. This will give you a nice introduction about how to contribute with Andes.
- [Wiki](https://github.com/mercadolibre/fury_andesui-android/wiki) has all the info you need to start with Andes. Even I heard there's a video there...

## Motivation
Tell us why you are here and why you took time to develop new code for our beloved lib.

## Description
Please describe your intentions with this new code you want to introduce inside Andes UI lib.
Try to answer those questions:
- What is it about?
- How does it work?

## Affected component
Is highly probable that this new code directly affects one (or more?) components inside this lib. Tell us who they are!

## Frontify component link
The UX team behind Andes keeps all the Andes Components inside the Frontify site. Each component has its own section. Let us know the section of the component you want to modify.

## Screenshots
This is a UI library, delight us with some stunning images.

## Checks
Are you sure you followed all those steps? In such case, let's say with me "I solemnly declare that ...":
- [ ] I have coded an example inside the Demo App,
- [ ] I have added proper tests,
- [ ] I have modified the [Changelog](https://github.com/mercadolibre/fury_andesui-android/blob/develop/CHANGELOG.md) file,
- [ ] I have updated GitHub wiki,
- [ ] I have the explicit approval of one or more members of the UX Team,
- [ ] I have updated the version in gradle.properties file.

## Change type
This is easy, let us know what this code is about:
- [ ] This code adds a new component
- [ ] This code includes improvements to an existent component
- [ ] This code improves or modifies ONLY the Demo App.

## Check common errors
Whether you are an Android or iOS developer and if you're still there then we'll give you a present:
https://proandroiddev.com/how-to-maximize-androids-ui-reusability-5-common-mistakes-cb2571216a9f

2021-02-05 18:31 UTC, eportasML commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/CoachmarkContainerView.kt
> +    fun setData(position: Int, size: Int) {
Estamos haciendo un breaking change aca. Por que?

2021-02-08 23:09 UTC, cvillamilmeli requested changes
Some changes to review

2021-02-08 23:09 UTC, cvillamilmeli commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/walkthroughmessage/WalkthroughMessageView.kt
> +    fun setListener(l: WalkthroughScrollessMessageView.WalkthroughButtonClicklistener) {
Don't use generic names for variables
```suggestion
    fun setListener(walkthroughButtonClicklistener: WalkthroughScrollessMessageView.WalkthroughButtonClicklistener) {
```

2021-02-08 23:09 UTC, cvillamilmeli commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/walkthroughmessage/WalkthroughMessageView.kt
> +    private var listener: WalkthroughScrollessMessageView.WalkthroughButtonClicklistener? = null
Don't use generic names for variables
```suggestion
    private var walkthroughButtonClicklistener: WalkthroughScrollessMessageView.WalkthroughButtonClicklistener? = null
```

2021-02-08 23:09 UTC, cvillamilmeli commented on coachmark/src/main/java/com/mercadolibre/android/andesui/coachmark/view/walkthroughmessage/WalkthroughMessageView.kt
> +        }
You can use [this function](https://github.com/mercadolibre/fury_andesui-android/pull/229/commits/39548e394d0ddddd40307b7a10b1f17a822b2070#diff-3f94a57502df05dc38f0e067adfdd773e2cd93bbcbedc9088ada343aca22fbafR132) also for this case

2021-02-08 23:09 UTC, cvillamilmeli commented on coachmark/src/main/res/layout/andes_walkthrough_message.xml
> +            android:textSize="16sp"
can you use dimens please

2021-02-09 13:40 UTC, agusanchez commented
@cvillamilmeli Ya quedaron los cambios en el PR.

2021-02-09 13:56 UTC, jperezgonzal commented on coachmark/src/main/res/layout/andes_walkthrough_container.xml
>          android:textSize="14sp"
Pasar esto a dimens

2021-02-09 13:56 UTC, jperezgonzal commented on coachmark/src/main/res/layout/andes_walkthrough_container.xml
>          android:layout_marginEnd="24dp"
Pasar esto a dimens

2021-02-09 13:56 UTC, jperezgonzal commented on coachmark/src/main/res/layout/andes_walkthrough_container.xml
>          app:layout_constraintGuide_begin="80dp" />
Pasar esto a dimens

2021-02-09 14:10 UTC, cvillamilmeli approved these changes

2021-02-09 14:13 UTC, merged